name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Your Commands
      run: |
        echo "Hello, GitHub Actions!"
        # Add your build/test/deploy commands here
